
obj-y += board_base.o misc.o spi_bus.o

obj-$(CONFIG_SOUND) += sound.o

obj-$(CONFIG_I2C_GPIO)          += i2c_bus.o
obj-$(CONFIG_I2C0_V12_JZ)       += i2c_bus.o
obj-$(CONFIG_I2C1_V12_JZ)       += i2c_bus.o
obj-$(CONFIG_I2C2_V12_JZ)       += i2c_bus.o
obj-$(CONFIG_I2C3_V12_JZ)       += i2c_bus.o

