# Makefile for the xburst sound oss driver
#
# 24 APR 2012, <jbbi: jbbi@ingernic.cn>
#

obj-$(CONFIG_SOUND_OSS_XBURST) 		+= devices/

obj-$(CONFIG_SOUND_OSS_XBURST) 		+= interface/ xb_snd_card.o

obj-$(CONFIG_SOUND_XBURST_DETECT)	+= xb_snd_detect.o

