#include "inc/sensors/libsensors_id.h"
#include "sensors.h"
#include "frizz_debug.h"

#define INPUT_SENSOR_TYPE_ID(code, id) code, id

struct {
    libsensors_type_e code;
    libsensors_id_e   id;
} sensor_list[] = {

    //Sensor Type of Android
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_FIFO_EMPTY,                  SENSOR_TYPE_FIFO_EMPTY)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ACCELEROMETER,               SENSOR_ID_ACCEL_RAW)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_MAGNETIC_FIELD,              SENSOR_ID_MAGNET_CALIB_HARD)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ORIENTATION,                 SENSOR_ID_ORIENTATION)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_GYROSCOPE,                   SENSOR_ID_GYRO_HPF)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_PRESSURE,                    SENSOR_ID_PRESSURE_RAW)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_GRAVITY,                     SENSOR_ID_GRAVITY)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_LINEAR_ACCELERATION,         SENSOR_ID_ACCEL_HPF)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ROTATION_VECTOR,             SENSOR_ID_ROTATION_VECTOR)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_MAGNETIC_FIELD_UNCALIBRATED, SENSOR_ID_MAGNET_UNCALIB)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_GAME_ROTATION_VECTOR,        SENSOR_ID_ROTATION_GRAVITY_VECTOR)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_GYROSCOPE_UNCALIBRATED,      SENSOR_ID_GYRO_UNCALIB)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_SIGNIFICANT_MOTION,          SENSOR_ID_ACCEL_MOVE)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_STEP_DETECTOR,               SENSOR_ID_ACCEL_STEP_DETECTOR)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_STEP_COUNTER,                SENSOR_ID_ACCEL_PEDOMETER)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_GEOMAGNETIC_ROTATION_VECTOR, SENSOR_ID_ROTATION_LPF_VECTOR)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_LIGHT,                       SENSOR_ID_LIGHT_RAW)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_PROXIMITY,                   SENSOR_ID_PROXIMITY)},
	{INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ACTIVITY,                    SENSOR_ID_ACTIVITY)},

     //Sensor Type of MCC
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_PDR, SENSOR_ID_PDR)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_MAGNET, SENSOR_ID_MAGNET_RAW)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_GYRO, SENSOR_ID_GYRO_RAW)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ACCEL_POWER, SENSOR_ID_ACCEL_POWER)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ACCEL_LPF, SENSOR_ID_ACCEL_LPF)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ACCEL_LINEAR, SENSOR_ID_ACCEL_LINEAR)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_MAGNET_PARAMETER, SENSOR_ID_MAGNET_PARAMETER)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_MAGNET_CALIB_SOFT, SENSOR_ID_MAGNET_CALIB_SOFT)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_MAGNET_LPF, SENSOR_ID_MAGNET_LPF)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_GYRO_LPF, SENSOR_ID_GYRO_LPF)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_DIRECTION, SENSOR_ID_DIRECTION)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_POSTURE, SENSOR_ID_POSTURE)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ROTATION_MATRIX, SENSOR_ID_ROTATION_MATRIX)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_VELOCITY, SENSOR_ID_VELOCITY)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_RELATIVE_POSITION, SENSOR_ID_RELATIVE_POSITION)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_MIGRATION_LENGTH, SENSOR_ID_MIGRATION_LENGTH)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_CYCLIC_TIMER, SENSOR_ID_CYCLIC_TIMER)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_DEBUG_QUEUE_IN, SENSOR_ID_DEBUG_QUEUE_IN)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_DEBUG_STD_IN, SENSOR_ID_DEBUG_STD_IN)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ISP, SENSOR_ID_ISP)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ACCEL_FALL_DOWN, SENSOR_ID_ACCEL_FALL_DOWN)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_ACCEL_POS_DET, SENSOR_ID_ACCEL_POS_DET)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_PDR_GEOFENCING, SENSOR_ID_PDR_GEOFENCING)},
    {INPUT_SENSOR_TYPE_ID(SENSOR_TYPE_GESTURE, SENSOR_ID_GESTURE)},
    {INPUT_SENSOR_TYPE_ID(HUB_MANAGER, HUB_MGR_ID)},
};

#define MAX_SENSOR_LIST_ELEMENT_COUNT  (sizeof(sensor_list) / sizeof(sensor_list[0]))

int convert_code_to_id(int code)
{
    int i;

    for (i = 0; i < MAX_SENSOR_LIST_ELEMENT_COUNT; i++) {
        if (sensor_list[i].code == code) {
            return sensor_list[i].id;
        }
    }

    return -1;
}

int convert_id_to_code(int id)
{
    int i;
    for (i = 0; i < MAX_SENSOR_LIST_ELEMENT_COUNT; i++) {
        if (sensor_list[i].id == id) {
            return sensor_list[i].code;
        }
    }

    return -1;
}



