
#ifndef __SERSORS_H__
#define __SERSORS_H__

/*!@enum Sensor type
 * @breaf Android Sensor type and MCC Sensor type
 */
typedef enum {

    //This const uses batch mode when frizz's software fifo is empty.
    SENSOR_TYPE_FIFO_EMPTY = 0,

    //These const are Android Senosr Type.
    SENSOR_TYPE_ACCELEROMETER = 1,
    SENSOR_TYPE_MAGNETIC_FIELD,
    SENSOR_TYPE_ORIENTATION,
    SENSOR_TYPE_GYROSCOPE,
    SENSOR_TYPE_LIGHT,
    SENSOR_TYPE_PRESSURE,
    SENSOR_TYPE_TEMPERATURE,
    SENSOR_TYPE_PROXIMITY,
    SENSOR_TYPE_GRAVITY,
    SENSOR_TYPE_LINEAR_ACCELERATION,
    SENSOR_TYPE_ROTATION_VECTOR,
    SENSOR_TYPE_RELATIVE_HUMIDITY,
    SENSOR_TYPE_AMBIENT_TEMPERATURE,
    SENSOR_TYPE_MAGNETIC_FIELD_UNCALIBRATED,
    SENSOR_TYPE_GAME_ROTATION_VECTOR,
    SENSOR_TYPE_GYROSCOPE_UNCALIBRATED,
    SENSOR_TYPE_SIGNIFICANT_MOTION,
    SENSOR_TYPE_STEP_DETECTOR,
    SENSOR_TYPE_STEP_COUNTER,
    SENSOR_TYPE_GEOMAGNETIC_ROTATION_VECTOR,

    //This const is MCC Sensor Type. (Extended Senosr)
    SENSOR_TYPE_PDR,    //21
    SENSOR_TYPE_MAGNET,
    SENSOR_TYPE_GYRO,
    SENSOR_TYPE_ACCEL_POWER,
    SENSOR_TYPE_ACCEL_LPF,
    SENSOR_TYPE_ACCEL_LINEAR,
    SENSOR_TYPE_MAGNET_PARAMETER,
    SENSOR_TYPE_MAGNET_CALIB_SOFT,
    SENSOR_TYPE_MAGNET_LPF,
    SENSOR_TYPE_GYRO_LPF,
    SENSOR_TYPE_DIRECTION,
    SENSOR_TYPE_POSTURE,
    SENSOR_TYPE_ROTATION_MATRIX,
    SENSOR_TYPE_VELOCITY,
    SENSOR_TYPE_RELATIVE_POSITION,
    SENSOR_TYPE_MIGRATION_LENGTH,
    SENSOR_TYPE_CYCLIC_TIMER,
    SENSOR_TYPE_DEBUG_QUEUE_IN,
    SENSOR_TYPE_DEBUG_STD_IN,
    SENSOR_TYPE_ISP,    //40
    SENSOR_TYPE_ACCEL_FALL_DOWN,
    SENSOR_TYPE_ACCEL_POS_DET,
    SENSOR_TYPE_PDR_GEOFENCING,
    SENSOR_TYPE_GESTURE,
	SENSOR_TYPE_ACTIVITY,
    HUB_MANAGER,
} libsensors_type_e;

#endif

