CFLAGS_KERNEL   += -I$(srctree)/arch/mips/xburst/soc-x1000/chip-x1000/$(CONFIG_PRODUCT_NAME)/$(CONFIG_BOARD_NAME)

obj-y       += common/
obj-$(CONFIG_BOARD_X1000_HALLEY2_V10)      += $(CONFIG_BOARD_NAME)/

