obj-$(CONFIG_MTD_NAND_JZBCH)		+= jz_bch.o
obj-$(CONFIG_MTD_NAND_JZNFI)		+= jz_nfi.o
obj-$(CONFIG_MTD_NAND_JZNEMC)		+= jz_nemc.o
obj-$(CONFIG_MTD_NAND_JZ_AUTO)		+= jz_nand_auto_params.o
obj-$(CONFIG_MTD_NAND_JZ_NORMAL)	+= jz_nand.o
